### ISSUE TITLE
[BUG] heap-buffer-overflow in ts::PESDemux::handlePESContent (found in asan+fuzz test)

### ISSUE THREAD

**Issue by svlobanov** [tsduck/tsduck#1423]
#### Bug description:
During fuzzing test (using `make ASAN=1` build) heap-buffer-overflow was found:

~~~
==5679==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000106506cf8 at pc 0x000102653a08 bp 0x00016fefe130 sp 0x00016fefe128
READ of size 1 at 0x000106506cf8 thread T4
    #0 0x102653a04 in ts::PESDemux::handlePESContent(ts::PESDemux::PIDContext&, ts::PESPacket const&) tsPESDemux.cpp:526
    #1 0x102650fb0 in ts::PESDemux::processPESPacket(unsigned short, ts::PESDemux::PIDContext&) tsPESDemux.cpp:405
    #2 0x102650324 in ts::PESDemux::processPacket(ts::TSPacket const&) tsPESDemux.cpp:183
    #3 0x1026500a0 in ts::PESDemux::feedPacket(ts::TSPacket const&) tsPESDemux.cpp:156
    #4 0x1002cd1ec in ts::PESPlugin::processPacket(ts::TSPacket&, ts::TSPacketMetadata&) tsplugin_pes.cpp:462
    #5 0x102cb3db8 in ts::tsp::ProcessorExecutor::processIndividualPackets() tstspProcessorExecutor.cpp:173
    #6 0x102cb3030 in ts::tsp::ProcessorExecutor::main() tstspProcessorExecutor.cpp:74
    #7 0x102abddfc in ts::Thread::mainWrapper() tsThread.cpp:345
    #8 0x102abd70c in ts::Thread::ThreadProc(void*) tsThread.cpp:389
    #9 0x18b9a5030 in _pthread_start+0x84 (libsystem_pthread.dylib:arm64e+0x7030)
    #10 0x18b99fe38 in thread_start+0x4 (libsystem_pthread.dylib:arm64e+0x1e38)

0x000106506cf8 is located 0 bytes after 184-byte region [0x000106506c40,0x000106506cf8)
allocated by thread T4 here:
    #0 0x1008c90ec in wrap__Znwm+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x610ec)
    #1 0x101f361a0 in std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>::__append(unsigned long) vector:1046
    #2 0x102053150 in ts::ByteBlock::copy(void const*, unsigned long) tsByteBlock.cpp:86
    #3 0x10265078c in ts::PESDemux::processPacket(ts::TSPacket const&) tsPESDemux.cpp:212
    #4 0x1026500a0 in ts::PESDemux::feedPacket(ts::TSPacket const&) tsPESDemux.cpp:156
    #5 0x1002cd1ec in ts::PESPlugin::processPacket(ts::TSPacket&, ts::TSPacketMetadata&) tsplugin_pes.cpp:462
    #6 0x102cb3db8 in ts::tsp::ProcessorExecutor::processIndividualPackets() tstspProcessorExecutor.cpp:173
    #7 0x102cb3030 in ts::tsp::ProcessorExecutor::main() tstspProcessorExecutor.cpp:74
    #8 0x102abddfc in ts::Thread::mainWrapper() tsThread.cpp:345
    #9 0x102abd70c in ts::Thread::ThreadProc(void*) tsThread.cpp:389
    #10 0x18b9a5030 in _pthread_start+0x84 (libsystem_pthread.dylib:arm64e+0x7030)
    #11 0x18b99fe38 in thread_start+0x4 (libsystem_pthread.dylib:arm64e+0x1e38)

Thread T4 created by T0 here:
    #0 0x1008b3b10 in wrap_pthread_create+0x54 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x4bb10)
    #1 0x102abd538 in ts::Thread::start() tsThread.cpp:245
    #2 0x1029e4840 in ts::TSProcessor::start(ts::TSProcessorArgs const&) tsTSProcessor.cpp:205
    #3 0x1000020a8 in MainCode(int, char**) tsp.cpp:147
    #4 0x102557a14 in MainWrapper(int (*)(int, char**), int, char**) tsMain.cpp:35
    #5 0x18b6290dc  (<unknown module>)

SUMMARY: AddressSanitizer: heap-buffer-overflow tsPESDemux.cpp:526 in ts::PESDemux::handlePESContent(ts::PESDemux::PIDContext&, ts::PESPacket const&)
~~~

#### How to reproduce:
1. Build tsduck with asan: `make -j9 ASAN=1` (on macos arm64 or linux x86_64)
2. Run `tsp -I file 040-1000-2000-2.ts -P pes --avc-access-unit --audio-attributes --intra-image --sei-avc --video-attributes -O drop`

TS file: [040-1000-2000-2.zip](https://github.com/tsduck/tsduck/files/13965481/040-1000-2000-2.zip)

#### Expected behavior:
no heap-buffer-overflow issue

#### Errors and logs:
I've added a very simple line to be sure that this issue is not false positive:
```
--- a/src/libtsduck/dtv/pes/tsPESDemux.cpp
+++ b/src/libtsduck/dtv/pes/tsPESDemux.cpp
@@ -523,6 +523,7 @@ void ts::PESDemux::handlePESContent(PIDContext& pc, const PESPacket& pes)
             const uint8_t* pnext = LocatePattern(pl_data + offset + 1, pl_size - offset - 1, StartCodePrefix, sizeof(StartCodePrefix));
             size_t next = pnext == nullptr ? pl_size : pnext - pl_data;
             // Invoke handler
+            std::cout << "pl_size=" << pl_size << " offset+3=" << offset + 3 << std::endl;
             _pes_handler->handleVideoStartCode(*this, pes, pl_data[offset + 3], offset, next - offset);
             // Accumulate info from video units to extract video attributes.
             // If new attributes were found, invoke handler.
```
If run with this printf-debug, then we can see:

~~~
...
pl_size=170 offset+3=3
pl_size=170 offset+3=12
pl_size=170 offset+3=21
pl_size=170 offset+3=94
pl_size=170 offset+3=110
pl_size=170 offset+3=138
pl_size=170 offset+3=170
~~~

So `pl_data[offset + 3]` code accesses 171st element, but pl_data size is 170

#### Environment:
 - OS: macOS
 - OS version: 14.1 
 - TSDuck full version: 3.37-3606
 - Installation type: rebuilt binary

#### Additional information:
no additional info

**Comment by lelegard** [comment]
Hi @svlobanov 

Well done, fixed...
