### ISSUE TITLE
[BUG] heap-buffer-overflow in ts::HEVCSequenceParameterSet::display (found in asan+fuzz test)

### ISSUE THREAD

**Issue by svlobanov** [tsduck/tsduck#1427]
#### Bug description:
During fuzzing test (using `make ASAN=1` build) heap-buffer-overflow was found:

~~~
==65512==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000105803628 at pc 0x000102d2026c bp 0x00016f5710d0 sp 0x00016f5710c8
READ of size 4 at 0x000105803628 thread T4
    #0 0x102d20268 in ts::HEVCSequenceParameterSet::display(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, ts::UString const&, int) const tsHEVCSequenceParameterSet.cpp:265
    #1 0x100d537ac in ts::PESPlugin::handleAccessUnit(ts::PESDemux&, ts::PESPacket const&, unsigned char, unsigned long, unsigned long) tsplugin_pes.cpp:720
    #2 0x102fd31a8 in ts::PESDemux::handlePESContent(ts::PESDemux::PIDContext&, ts::PESPacket const&) tsPESDemux.cpp:472
    #3 0x102fd0d54 in ts::PESDemux::processPESPacket(unsigned short, ts::PESDemux::PIDContext&) tsPESDemux.cpp:405
    #4 0x102fd05a8 in ts::PESDemux::processPacket(ts::TSPacket const&) tsPESDemux.cpp
    #5 0x102fcfe44 in ts::PESDemux::feedPacket(ts::TSPacket const&) tsPESDemux.cpp:156
    #6 0x100d4d1ec in ts::PESPlugin::processPacket(ts::TSPacket&, ts::TSPacketMetadata&) tsplugin_pes.cpp:462
    #7 0x103633d78 in ts::tsp::ProcessorExecutor::processIndividualPackets() tstspProcessorExecutor.cpp:173
    #8 0x103632ff0 in ts::tsp::ProcessorExecutor::main() tstspProcessorExecutor.cpp:74
    #9 0x10343dd48 in ts::Thread::mainWrapper() tsThread.cpp:345
    #10 0x10343d658 in ts::Thread::ThreadProc(void*) tsThread.cpp:389
...
~~~

#### How to reproduce:
1. Build tsduck with asan: `make -j9 ASAN=1` (on macos arm64 or linux x86_64)
2. Run `tsp -I file test-100.2-fuzz.ts -P pes --pid 0x01E1 --avc-access-unit --h26x-default-format hevc -O drop`

TS file: [test-100.2-fuzz.zip](https://github.com/tsduck/tsduck/files/13969995/test-100.2-fuzz.zip)

#### Expected behavior:
no heap-buffer-overflow issue

#### Environment:
 - OS: macOS
 - OS version: 14.1
 - TSDuck full version: 3.37-3611
 - Installation type: rebuilt binary

#### Additional information:
no additional info

**Comment by lelegard** [comment]
Fixed.
